# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: get github run number
        run: echo $GITHUB_RUN_NUMBER
        
      - name: Hello World
        uses: actions/hello-world-javascript-action/@v1
        with:
          who-to-greet: 'Mona the Lioncat'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}'
      - shell: bash
        env:
          key:  ${{ secrets.secret_key1 }}
        run: |
          echo "$key"
